# Generated by Django 5.2.1 on 2025-06-02 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название статуса'),
        ),
        migrations.CreateModel(
            name='CompanyStatusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_status_docs/%Y/%m/%d/', verbose_name='PDF-файл')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_documents', to='main.company', verbose_name='Компания')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='main.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Документ (компания + статус)',
                'verbose_name_plural': 'Документы (компания + статус)',
            },
        ),
    ]
