# Generated by Django 5.2.1 on 2025-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_status_name_companystatusdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], max_length=3, unique=True, verbose_name='Код региона')),
                ('name', models.CharField(max_length=50, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Выберите один или несколько регионов', to='main.region', verbose_name='Регионы пользователя'),
        ),
    ]
