# Generated by Django 5.2.1 on 2025-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_region_remove_profile_region_profile_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bin_number',
            field=models.CharField(blank=True, help_text='Бизнес-идентификационный номер (необязательно)', max_length=50, null=True, verbose_name='БИН'),
        ),
        migrations.AddField(
            model_name='company',
            name='debt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма долга (необязательно)', max_digits=12, null=True, verbose_name='Сумма долга'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Имя ответственного лица/управляющего (необязательно)', max_length=150, null=True, verbose_name='Управляющий'),
        ),
    ]
