# Generated by Django 5.2.1 on 2025-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_company_bin_number_company_debt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Название компании'),
        ),
    ]
