# Generated by Django 5.1.9 on 2025-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_companystatushistory_is_paused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystatushistory',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Флаг: этот этап приостановлен?', verbose_name='На паузе'),
        ),
        migrations.AlterField(
            model_name='companystatushistory',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Если этап на паузе, когда именно он был поставлен на паузу', null=True, verbose_name='Когда поставили на паузу'),
        ),
    ]
