# Generated by Django 5.1.9 on 2025-06-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_companystatushistory_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='repaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма уже погашенного долга (если есть)', max_digits=12, null=True, verbose_name='Сумма погашения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если это комментарий к компании в целом', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_comments', to='main.status', verbose_name='Этап (если комментарий к этапу)'),
        ),
    ]
