# Generated by Django 5.1.9 on 2025-06-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_company_repaid_amount_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Географический регион компании', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион'),
        ),
    ]
