# Generated by Django 5.1.9 on 2025-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_company_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], default='KST', help_text='Географический регион компании', max_length=3, verbose_name='Регион'),
        ),
    ]
