# Generated by Django 5.1.9 on 2025-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_company_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
